// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'8e5df303ee55024e56d64adc8f06324f7b5261084cc50406929fca0e76b59f43'>;
export type ExecutionHash =
  ExecutionHashBase<'627beaa08b0349bbb5a3e3aafbab0e3e8476071646fd4626fef2b6f989842c8a'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly avis_de_valeur: {
    readonly AvisDeValeur: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly conseillerIdapimo: CodecTypes['pg/int4@1']['output'];
      readonly type: 'maison' | 'appartement';
      readonly statut: 'brouillon' | 'enregistre';
      readonly clientNom: CodecTypes['pg/text@1']['output'] | null;
      readonly clientTelephone: CodecTypes['pg/text@1']['output'] | null;
      readonly clientEmail: CodecTypes['pg/text@1']['output'] | null;
      readonly adresse: CodecTypes['pg/text@1']['output'] | null;
      readonly codePostal: CodecTypes['pg/text@1']['output'] | null;
      readonly ville: CodecTypes['pg/text@1']['output'] | null;
      readonly surfaceHabitable: CodecTypes['pg/numeric@1']['output'] | null;
      readonly prixM2: CodecTypes['pg/numeric@1']['output'] | null;
      readonly surfaceMedianeQuartier: CodecTypes['pg/numeric@1']['output'] | null;
      readonly dpe: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | null;
      readonly tendanceCran: 'haussier' | 'equilibre' | 'baissier';
      readonly tendancePourcentage: CodecTypes['pg/numeric@1']['output'];
      readonly valeurIntrinseque: CodecTypes['pg/numeric@1']['output'] | null;
      readonly valeurRetenue: CodecTypes['pg/numeric@1']['output'] | null;
      readonly referentielVersionId: CodecTypes['pg/uuid@1']['output'];
      readonly creeLe: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly modifieLe: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly supprimeLe: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly LigneAvis: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly avisId: CodecTypes['pg/uuid@1']['output'];
      readonly categorie: 'majoration' | 'minoration';
      readonly cle: CodecTypes['pg/text@1']['output'];
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly kind: 'surface' | 'pourcentage' | 'coutM2' | 'montant' | 'options' | 'interrupteur';
      readonly surface: CodecTypes['pg/numeric@1']['output'] | null;
      readonly pourcentage: CodecTypes['pg/numeric@1']['output'] | null;
      readonly coutM2: CodecTypes['pg/numeric@1']['output'] | null;
      readonly montant: CodecTypes['pg/numeric@1']['output'] | null;
      readonly option: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly ReferentielVersion: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly contenu: CodecTypes['pg/jsonb@1']['output'];
      readonly actif: CodecTypes['pg/bool@1']['output'];
      readonly creeLe: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly creeParIdapimo: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Session: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly tokenHash: CodecTypes['pg/text@1']['output'];
      readonly conseillerIdapimo: CodecTypes['pg/int4@1']['output'];
      readonly creeLe: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly expireLe: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly vuLe: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly userAgent: CodecTypes['pg/text@1']['output'] | null;
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly TentativeConnexion: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly reussie: CodecTypes['pg/bool@1']['output'];
      readonly creeLe: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
  readonly public: {
    readonly Utilisateur: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idapimo: CodecTypes['pg/int4@1']['output'];
      readonly prenom: Varchar<50> | null;
      readonly nom: Varchar<50> | null;
      readonly email: Varchar<255> | null;
      readonly telephone: Varchar<60> | null;
      readonly mobile: Varchar<60> | null;
      readonly role: Varchar<50> | null;
      readonly actif: CodecTypes['pg/bool@1']['output'];
      readonly motDePasse: Char<60> | null;
      readonly siren: Varchar<255> | null;
    };
  };
};
export type FieldInputTypes = {
  readonly avis_de_valeur: {
    readonly AvisDeValeur: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly conseillerIdapimo: CodecTypes['pg/int4@1']['input'];
      readonly type: 'maison' | 'appartement';
      readonly statut: 'brouillon' | 'enregistre';
      readonly clientNom: CodecTypes['pg/text@1']['input'] | null;
      readonly clientTelephone: CodecTypes['pg/text@1']['input'] | null;
      readonly clientEmail: CodecTypes['pg/text@1']['input'] | null;
      readonly adresse: CodecTypes['pg/text@1']['input'] | null;
      readonly codePostal: CodecTypes['pg/text@1']['input'] | null;
      readonly ville: CodecTypes['pg/text@1']['input'] | null;
      readonly surfaceHabitable: CodecTypes['pg/numeric@1']['input'] | null;
      readonly prixM2: CodecTypes['pg/numeric@1']['input'] | null;
      readonly surfaceMedianeQuartier: CodecTypes['pg/numeric@1']['input'] | null;
      readonly dpe: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | null;
      readonly tendanceCran: 'haussier' | 'equilibre' | 'baissier';
      readonly tendancePourcentage: CodecTypes['pg/numeric@1']['input'];
      readonly valeurIntrinseque: CodecTypes['pg/numeric@1']['input'] | null;
      readonly valeurRetenue: CodecTypes['pg/numeric@1']['input'] | null;
      readonly referentielVersionId: CodecTypes['pg/uuid@1']['input'];
      readonly creeLe: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly modifieLe: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly supprimeLe: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly LigneAvis: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly avisId: CodecTypes['pg/uuid@1']['input'];
      readonly categorie: 'majoration' | 'minoration';
      readonly cle: CodecTypes['pg/text@1']['input'];
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly kind: 'surface' | 'pourcentage' | 'coutM2' | 'montant' | 'options' | 'interrupteur';
      readonly surface: CodecTypes['pg/numeric@1']['input'] | null;
      readonly pourcentage: CodecTypes['pg/numeric@1']['input'] | null;
      readonly coutM2: CodecTypes['pg/numeric@1']['input'] | null;
      readonly montant: CodecTypes['pg/numeric@1']['input'] | null;
      readonly option: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly ReferentielVersion: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly contenu: CodecTypes['pg/jsonb@1']['input'];
      readonly actif: CodecTypes['pg/bool@1']['input'];
      readonly creeLe: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly creeParIdapimo: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Session: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly tokenHash: CodecTypes['pg/text@1']['input'];
      readonly conseillerIdapimo: CodecTypes['pg/int4@1']['input'];
      readonly creeLe: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly expireLe: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly vuLe: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly userAgent: CodecTypes['pg/text@1']['input'] | null;
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly TentativeConnexion: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly reussie: CodecTypes['pg/bool@1']['input'];
      readonly creeLe: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
  readonly public: {
    readonly Utilisateur: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idapimo: CodecTypes['pg/int4@1']['input'];
      readonly prenom: CodecTypes['sql/varchar@1']['input'] | null;
      readonly nom: CodecTypes['sql/varchar@1']['input'] | null;
      readonly email: CodecTypes['sql/varchar@1']['input'] | null;
      readonly telephone: CodecTypes['sql/varchar@1']['input'] | null;
      readonly mobile: CodecTypes['sql/varchar@1']['input'] | null;
      readonly role: CodecTypes['sql/varchar@1']['input'] | null;
      readonly actif: CodecTypes['pg/bool@1']['input'];
      readonly motDePasse: CodecTypes['sql/char@1']['input'] | null;
      readonly siren: CodecTypes['sql/varchar@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly avis_de_valeur: {
    readonly avis_de_valeur: {
      readonly adresse: CodecTypes['pg/text@1']['output'] | null;
      readonly client_email: CodecTypes['pg/text@1']['output'] | null;
      readonly client_nom: CodecTypes['pg/text@1']['output'] | null;
      readonly client_telephone: CodecTypes['pg/text@1']['output'] | null;
      readonly code_postal: CodecTypes['pg/text@1']['output'] | null;
      readonly conseiller_idapimo: CodecTypes['pg/int4@1']['output'];
      readonly cree_le: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly dpe: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly modifie_le: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly prix_m2: CodecTypes['pg/numeric@1']['output'] | null;
      readonly referentiel_version_id: CodecTypes['pg/uuid@1']['output'];
      readonly statut: 'brouillon' | 'enregistre';
      readonly supprime_le: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly surface_habitable: CodecTypes['pg/numeric@1']['output'] | null;
      readonly surface_mediane_quartier: CodecTypes['pg/numeric@1']['output'] | null;
      readonly tendance_cran: 'haussier' | 'equilibre' | 'baissier';
      readonly tendance_pourcentage: CodecTypes['pg/numeric@1']['output'];
      readonly type: 'maison' | 'appartement';
      readonly valeur_intrinseque: CodecTypes['pg/numeric@1']['output'] | null;
      readonly valeur_retenue: CodecTypes['pg/numeric@1']['output'] | null;
      readonly ville: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly ligne_avis: {
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly avis_id: CodecTypes['pg/uuid@1']['output'];
      readonly categorie: 'majoration' | 'minoration';
      readonly cle: CodecTypes['pg/text@1']['output'];
      readonly cout_m2: CodecTypes['pg/numeric@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly kind: 'surface' | 'pourcentage' | 'coutM2' | 'montant' | 'options' | 'interrupteur';
      readonly montant: CodecTypes['pg/numeric@1']['output'] | null;
      readonly option: CodecTypes['pg/text@1']['output'] | null;
      readonly pourcentage: CodecTypes['pg/numeric@1']['output'] | null;
      readonly surface: CodecTypes['pg/numeric@1']['output'] | null;
    };
    readonly referentiel_version: {
      readonly actif: CodecTypes['pg/bool@1']['output'];
      readonly contenu: CodecTypes['pg/jsonb@1']['output'];
      readonly cree_le: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly cree_par_idapimo: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly session: {
      readonly conseiller_idapimo: CodecTypes['pg/int4@1']['output'];
      readonly cree_le: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly expire_le: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly token_hash: CodecTypes['pg/text@1']['output'];
      readonly user_agent: CodecTypes['pg/text@1']['output'] | null;
      readonly vu_le: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly tentative_connexion: {
      readonly cree_le: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ip: CodecTypes['pg/text@1']['output'] | null;
      readonly reussie: CodecTypes['pg/bool@1']['output'];
    };
  };
  readonly public: {
    readonly utilisateurs: {
      readonly actif: CodecTypes['pg/bool@1']['output'];
      readonly email: Varchar<255> | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idapimo: CodecTypes['pg/int4@1']['output'];
      readonly mobile: Varchar<60> | null;
      readonly motDePasse: Char<60> | null;
      readonly nom: Varchar<50> | null;
      readonly prenom: Varchar<50> | null;
      readonly role: Varchar<50> | null;
      readonly siren: Varchar<255> | null;
      readonly telephone: Varchar<60> | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly avis_de_valeur: {
    readonly avis_de_valeur: {
      readonly adresse: CodecTypes['pg/text@1']['input'] | null;
      readonly client_email: CodecTypes['pg/text@1']['input'] | null;
      readonly client_nom: CodecTypes['pg/text@1']['input'] | null;
      readonly client_telephone: CodecTypes['pg/text@1']['input'] | null;
      readonly code_postal: CodecTypes['pg/text@1']['input'] | null;
      readonly conseiller_idapimo: CodecTypes['pg/int4@1']['input'];
      readonly cree_le: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly dpe: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly modifie_le: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly prix_m2: CodecTypes['pg/numeric@1']['input'] | null;
      readonly referentiel_version_id: CodecTypes['pg/uuid@1']['input'];
      readonly statut: 'brouillon' | 'enregistre';
      readonly supprime_le: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly surface_habitable: CodecTypes['pg/numeric@1']['input'] | null;
      readonly surface_mediane_quartier: CodecTypes['pg/numeric@1']['input'] | null;
      readonly tendance_cran: 'haussier' | 'equilibre' | 'baissier';
      readonly tendance_pourcentage: CodecTypes['pg/numeric@1']['input'];
      readonly type: 'maison' | 'appartement';
      readonly valeur_intrinseque: CodecTypes['pg/numeric@1']['input'] | null;
      readonly valeur_retenue: CodecTypes['pg/numeric@1']['input'] | null;
      readonly ville: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly ligne_avis: {
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly avis_id: CodecTypes['pg/uuid@1']['input'];
      readonly categorie: 'majoration' | 'minoration';
      readonly cle: CodecTypes['pg/text@1']['input'];
      readonly cout_m2: CodecTypes['pg/numeric@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly kind: 'surface' | 'pourcentage' | 'coutM2' | 'montant' | 'options' | 'interrupteur';
      readonly montant: CodecTypes['pg/numeric@1']['input'] | null;
      readonly option: CodecTypes['pg/text@1']['input'] | null;
      readonly pourcentage: CodecTypes['pg/numeric@1']['input'] | null;
      readonly surface: CodecTypes['pg/numeric@1']['input'] | null;
    };
    readonly referentiel_version: {
      readonly actif: CodecTypes['pg/bool@1']['input'];
      readonly contenu: CodecTypes['pg/jsonb@1']['input'];
      readonly cree_le: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly cree_par_idapimo: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly session: {
      readonly conseiller_idapimo: CodecTypes['pg/int4@1']['input'];
      readonly cree_le: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly expire_le: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly token_hash: CodecTypes['pg/text@1']['input'];
      readonly user_agent: CodecTypes['pg/text@1']['input'] | null;
      readonly vu_le: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly tentative_connexion: {
      readonly cree_le: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ip: CodecTypes['pg/text@1']['input'] | null;
      readonly reussie: CodecTypes['pg/bool@1']['input'];
    };
  };
  readonly public: {
    readonly utilisateurs: {
      readonly actif: CodecTypes['pg/bool@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idapimo: CodecTypes['pg/int4@1']['input'];
      readonly mobile: CodecTypes['sql/varchar@1']['input'] | null;
      readonly motDePasse: CodecTypes['sql/char@1']['input'] | null;
      readonly nom: CodecTypes['sql/varchar@1']['input'] | null;
      readonly prenom: CodecTypes['sql/varchar@1']['input'] | null;
      readonly role: CodecTypes['sql/varchar@1']['input'] | null;
      readonly siren: CodecTypes['sql/varchar@1']['input'] | null;
      readonly telephone: CodecTypes['sql/varchar@1']['input'] | null;
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly avis_de_valeur: {
        readonly id: 'avis_de_valeur';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly avis_de_valeur: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly conseiller_idapimo: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly statut: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'brouillon'>;
                  };
                };
                readonly client_nom: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly client_telephone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly client_email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly adresse: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly code_postal: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly ville: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly surface_habitable: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly prix_m2: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly surface_mediane_quartier: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly dpe: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly tendance_cran: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'equilibre'>;
                  };
                };
                readonly tendance_pourcentage: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/numeric@1', '0'>;
                  };
                };
                readonly valeur_intrinseque: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly valeur_retenue: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly referentiel_version_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly cree_le: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly modifie_le: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly supprime_le: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'avis_de_valeur_conseiller_idapimo_modifie_le_idx_2531ff6b';
                  readonly prefix: 'avis_de_valeur_conseiller_idapimo_modifie_le_idx';
                  readonly columns: readonly ['conseiller_idapimo', 'modifie_le'];
                  readonly unique: false;
                },
                {
                  readonly name: 'avis_de_valeur_referentiel_version_id_idx_ba6ba763';
                  readonly prefix: 'avis_de_valeur_referentiel_version_id_idx';
                  readonly columns: readonly ['referentiel_version_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'avis_de_valeur_conseiller_idapimo_idx_f7c90b50';
                  readonly prefix: 'avis_de_valeur_conseiller_idapimo_idx';
                  readonly columns: readonly ['conseiller_idapimo'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'avis_de_valeur' & NamespaceId;
                    readonly tableName: 'avis_de_valeur';
                    readonly columns: readonly ['conseiller_idapimo'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'utilisateurs';
                    readonly columns: readonly ['idapimo'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'avis_de_valeur' & NamespaceId;
                    readonly tableName: 'avis_de_valeur';
                    readonly columns: readonly ['referentiel_version_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'avis_de_valeur' & NamespaceId;
                    readonly tableName: 'referentiel_version';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly ligne_avis: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly avis_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly categorie: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cle: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly kind: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly surface: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly pourcentage: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly cout_m2: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly montant: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly option: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['avis_id', 'cle'] }];
              indexes: readonly [
                {
                  readonly name: 'ligne_avis_avis_id_idx_1be523a4';
                  readonly prefix: 'ligne_avis_avis_id_idx';
                  readonly columns: readonly ['avis_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'avis_de_valeur' & NamespaceId;
                    readonly tableName: 'ligne_avis';
                    readonly columns: readonly ['avis_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'avis_de_valeur' & NamespaceId;
                    readonly tableName: 'avis_de_valeur';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly referentiel_version: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly contenu: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly actif: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly cree_le: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly cree_par_idapimo: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'referentiel_version_actif_idx_a7f19943';
                  readonly prefix: 'referentiel_version_actif_idx';
                  readonly columns: readonly ['actif'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly session: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly token_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly conseiller_idapimo: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly cree_le: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly expire_le: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly vu_le: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly user_agent: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly ip: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['token_hash'] }];
              indexes: readonly [
                {
                  readonly name: 'session_conseiller_idapimo_idx_f7c90b50';
                  readonly prefix: 'session_conseiller_idapimo_idx';
                  readonly columns: readonly ['conseiller_idapimo'];
                  readonly unique: false;
                },
                {
                  readonly name: 'session_expire_le_idx_f9e8e926';
                  readonly prefix: 'session_expire_le_idx';
                  readonly columns: readonly ['expire_le'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'avis_de_valeur' & NamespaceId;
                    readonly tableName: 'session';
                    readonly columns: readonly ['conseiller_idapimo'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'utilisateurs';
                    readonly columns: readonly ['idapimo'];
                  };
                },
              ];
            };
            readonly tentative_connexion: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ip: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly reussie: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly cree_le: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'tentative_connexion_email_cree_le_idx_4d6429d3';
                  readonly prefix: 'tentative_connexion_email_cree_le_idx';
                  readonly columns: readonly ['email', 'cree_le'];
                  readonly unique: false;
                },
                {
                  readonly name: 'tentative_connexion_ip_cree_le_idx_e9728ccb';
                  readonly prefix: 'tentative_connexion_ip_cree_le_idx';
                  readonly columns: readonly ['ip', 'cree_le'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
          };
        };
      };
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly utilisateurs: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly idapimo: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly prenom: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly nom: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly telephone: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 60 };
                };
                readonly mobile: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 60 };
                };
                readonly role: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly actif: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly motDePasse: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 60 };
                };
                readonly siren: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'utilisateurs_pkey' };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idapimo_unique';
                  readonly columns: readonly ['idapimo'];
                  readonly unique: true;
                },
              ];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly categorie_ligne: {
              readonly kind: 'valueSet';
              readonly values: readonly ['majoration', 'minoration'];
            };
            readonly cran_tendance: {
              readonly kind: 'valueSet';
              readonly values: readonly ['haussier', 'equilibre', 'baissier'];
            };
            readonly kind_ligne: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'surface',
                'pourcentage',
                'coutM2',
                'montant',
                'options',
                'interrupteur',
              ];
            };
            readonly lettre_dpe: {
              readonly kind: 'valueSet';
              readonly values: readonly ['A', 'B', 'C', 'D', 'E', 'F', 'G'];
            };
            readonly statut_avis: {
              readonly kind: 'valueSet';
              readonly values: readonly ['brouillon', 'enregistre'];
            };
            readonly type_bien: {
              readonly kind: 'valueSet';
              readonly values: readonly ['maison', 'appartement'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly utilisateurs: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Utilisateur';
    };
    readonly session: {
      readonly namespace: 'avis_de_valeur' & NamespaceId;
      readonly model: 'Session';
    };
    readonly tentative_connexion: {
      readonly namespace: 'avis_de_valeur' & NamespaceId;
      readonly model: 'TentativeConnexion';
    };
    readonly referentiel_version: {
      readonly namespace: 'avis_de_valeur' & NamespaceId;
      readonly model: 'ReferentielVersion';
    };
    readonly avis_de_valeur: {
      readonly namespace: 'avis_de_valeur' & NamespaceId;
      readonly model: 'AvisDeValeur';
    };
    readonly ligne_avis: {
      readonly namespace: 'avis_de_valeur' & NamespaceId;
      readonly model: 'LigneAvis';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly avis_de_valeur: {
        readonly models: {
          readonly AvisDeValeur: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly conseillerIdapimo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly statut: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly clientNom: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly clientTelephone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly clientEmail: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly adresse: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly codePostal: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ville: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly surfaceHabitable: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly prixM2: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly surfaceMedianeQuartier: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly dpe: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tendanceCran: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tendancePourcentage: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly valeurIntrinseque: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly valeurRetenue: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly referentielVersionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly creeLe: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly modifieLe: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly supprimeLe: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly conseiller: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Utilisateur';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['conseillerIdapimo'];
                  readonly targetFields: readonly ['idapimo'];
                };
              };
              readonly lignes: {
                readonly to: {
                  readonly namespace: 'avis_de_valeur' & NamespaceId;
                  readonly model: 'LigneAvis';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['avisId'];
                };
              };
              readonly referentielVersion: {
                readonly to: {
                  readonly namespace: 'avis_de_valeur' & NamespaceId;
                  readonly model: 'ReferentielVersion';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['referentielVersionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'avis_de_valeur';
              readonly namespaceId: 'avis_de_valeur';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly conseillerIdapimo: { readonly column: 'conseiller_idapimo' };
                readonly type: { readonly column: 'type' };
                readonly statut: { readonly column: 'statut' };
                readonly clientNom: { readonly column: 'client_nom' };
                readonly clientTelephone: { readonly column: 'client_telephone' };
                readonly clientEmail: { readonly column: 'client_email' };
                readonly adresse: { readonly column: 'adresse' };
                readonly codePostal: { readonly column: 'code_postal' };
                readonly ville: { readonly column: 'ville' };
                readonly surfaceHabitable: { readonly column: 'surface_habitable' };
                readonly prixM2: { readonly column: 'prix_m2' };
                readonly surfaceMedianeQuartier: { readonly column: 'surface_mediane_quartier' };
                readonly dpe: { readonly column: 'dpe' };
                readonly tendanceCran: { readonly column: 'tendance_cran' };
                readonly tendancePourcentage: { readonly column: 'tendance_pourcentage' };
                readonly valeurIntrinseque: { readonly column: 'valeur_intrinseque' };
                readonly valeurRetenue: { readonly column: 'valeur_retenue' };
                readonly referentielVersionId: { readonly column: 'referentiel_version_id' };
                readonly creeLe: { readonly column: 'cree_le' };
                readonly modifieLe: { readonly column: 'modifie_le' };
                readonly supprimeLe: { readonly column: 'supprime_le' };
              };
            };
          };
          readonly LigneAvis: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly avisId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly categorie: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cle: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly surface: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly pourcentage: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly coutM2: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly montant: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly option: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly avis: {
                readonly to: {
                  readonly namespace: 'avis_de_valeur' & NamespaceId;
                  readonly model: 'AvisDeValeur';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['avisId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ligne_avis';
              readonly namespaceId: 'avis_de_valeur';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly avisId: { readonly column: 'avis_id' };
                readonly categorie: { readonly column: 'categorie' };
                readonly cle: { readonly column: 'cle' };
                readonly active: { readonly column: 'active' };
                readonly kind: { readonly column: 'kind' };
                readonly surface: { readonly column: 'surface' };
                readonly pourcentage: { readonly column: 'pourcentage' };
                readonly coutM2: { readonly column: 'cout_m2' };
                readonly montant: { readonly column: 'montant' };
                readonly option: { readonly column: 'option' };
              };
            };
          };
          readonly ReferentielVersion: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly contenu: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly actif: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly creeLe: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly creeParIdapimo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly avis: {
                readonly to: {
                  readonly namespace: 'avis_de_valeur' & NamespaceId;
                  readonly model: 'AvisDeValeur';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['referentielVersionId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'referentiel_version';
              readonly namespaceId: 'avis_de_valeur';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly contenu: { readonly column: 'contenu' };
                readonly actif: { readonly column: 'actif' };
                readonly creeLe: { readonly column: 'cree_le' };
                readonly creeParIdapimo: { readonly column: 'cree_par_idapimo' };
              };
            };
          };
          readonly Session: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly tokenHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly conseillerIdapimo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly creeLe: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly expireLe: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly vuLe: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly userAgent: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ip: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly conseiller: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Utilisateur';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['conseillerIdapimo'];
                  readonly targetFields: readonly ['idapimo'];
                };
              };
            };
            readonly storage: {
              readonly table: 'session';
              readonly namespaceId: 'avis_de_valeur';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly tokenHash: { readonly column: 'token_hash' };
                readonly conseillerIdapimo: { readonly column: 'conseiller_idapimo' };
                readonly creeLe: { readonly column: 'cree_le' };
                readonly expireLe: { readonly column: 'expire_le' };
                readonly vuLe: { readonly column: 'vu_le' };
                readonly userAgent: { readonly column: 'user_agent' };
                readonly ip: { readonly column: 'ip' };
              };
            };
          };
          readonly TentativeConnexion: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ip: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reussie: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly creeLe: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'tentative_connexion';
              readonly namespaceId: 'avis_de_valeur';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly ip: { readonly column: 'ip' };
                readonly reussie: { readonly column: 'reussie' };
                readonly creeLe: { readonly column: 'cree_le' };
              };
            };
          };
        };
      };
      readonly public: {
        readonly models: {
          readonly Utilisateur: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idapimo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly prenom: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly nom: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly telephone: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 60 };
                };
              };
              readonly mobile: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 60 };
                };
              };
              readonly role: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly actif: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly motDePasse: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 60 };
                };
              };
              readonly siren: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'utilisateurs';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly idapimo: { readonly column: 'idapimo' };
                readonly prenom: { readonly column: 'prenom' };
                readonly nom: { readonly column: 'nom' };
                readonly email: { readonly column: 'email' };
                readonly telephone: { readonly column: 'telephone' };
                readonly mobile: { readonly column: 'mobile' };
                readonly role: { readonly column: 'role' };
                readonly actif: { readonly column: 'actif' };
                readonly motDePasse: { readonly column: 'motDePasse' };
                readonly siren: { readonly column: 'siren' };
              };
            };
          };
        };
        readonly enum: {
          readonly type_bien: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'maison'; readonly value: 'maison' },
              { readonly name: 'appartement'; readonly value: 'appartement' },
            ];
          };
          readonly statut_avis: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'brouillon'; readonly value: 'brouillon' },
              { readonly name: 'enregistre'; readonly value: 'enregistre' },
            ];
          };
          readonly lettre_dpe: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'A'; readonly value: 'A' },
              { readonly name: 'B'; readonly value: 'B' },
              { readonly name: 'C'; readonly value: 'C' },
              { readonly name: 'D'; readonly value: 'D' },
              { readonly name: 'E'; readonly value: 'E' },
              { readonly name: 'F'; readonly value: 'F' },
              { readonly name: 'G'; readonly value: 'G' },
            ];
          };
          readonly cran_tendance: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'haussier'; readonly value: 'haussier' },
              { readonly name: 'equilibre'; readonly value: 'equilibre' },
              { readonly name: 'baissier'; readonly value: 'baissier' },
            ];
          };
          readonly categorie_ligne: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'majoration'; readonly value: 'majoration' },
              { readonly name: 'minoration'; readonly value: 'minoration' },
            ];
          };
          readonly kind_ligne: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'surface'; readonly value: 'surface' },
              { readonly name: 'pourcentage'; readonly value: 'pourcentage' },
              { readonly name: 'coutM2'; readonly value: 'coutM2' },
              { readonly name: 'montant'; readonly value: 'montant' },
              { readonly name: 'options'; readonly value: 'options' },
              { readonly name: 'interrupteur'; readonly value: 'interrupteur' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'avis_de_valeur';
            readonly table: 'avis_de_valeur';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'avis_de_valeur';
            readonly table: 'ligne_avis';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'avis_de_valeur';
            readonly table: 'referentiel_version';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'avis_de_valeur';
            readonly table: 'session';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'avis_de_valeur';
            readonly table: 'tentative_connexion';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
